### ISSUE TITLE
Add Data Supply components to prototype 1.0

### ISSUE THREAD

**Issue by Helmikalle** [EUMETNET/community-component-apim#5]
Agreement which Data supply is used for the prototype

**Comment by JaneWardle** [comment]
Includes
Roope (EUMETSAT) fetch OPERA radar data files and add on S3

**Comment by JaneWardle** [comment]
Annakaisa (OPERA Radar lead) will review the list and reply with comments and suggested changes.

**Comment by eetuniemi** [comment]
Add new data supplies to prototype 1.0
